openapi: 3.1.0
info:
  title: Devolutions PEDM API
  version: ""
servers:
- url: /
paths:
  /about:
    get:
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: ""
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AboutData'
          description: ""
  /elevate/temporary:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ElevateTemporaryPayload'
        required: true
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: ""
        "200":
          description: no content
  /elevate/session:
    post:
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: ""
        "200":
          description: no content
  /launch:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LaunchPayload'
        required: true
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: ""
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LaunchResponse'
          description: ""
  /revoke:
    post:
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: ""
        "200":
          description: no content
  /status:
    get:
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: ""
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
          description: ""
  /log/jit:
    get:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JitElevationLogQueryOptions'
        required: true
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: ""
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JitElevationLogPage'
          description: ""
  /policy/me:
    get:
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: ""
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetProfilesMeResponse'
          description: |-
            Returns some information about the current user and active profiles.

            If there is no active profile, the `active` UUID will be full of zeroes.
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OptionalId'
        required: true
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: ""
        "200":
          description: no content
  /policy/profiles:
    get:
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: ""
        "200":
          content:
            application/json:
              schema:
                items:
                  format: uuid
                  type: string
                type: array
          description: ""
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Profile'
        required: true
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: ""
        "200":
          description: no content
  /policy/profiles/{id}:
    delete:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: ""
        "200":
          description: no content
    get:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: ""
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
          description: ""
    put:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Profile'
        required: true
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: ""
        "200":
          description: no content
  /policy/assignments:
    get:
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: ""
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Assignment'
                type: array
          description: ""
  /policy/assignments/{id}:
    put:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              items:
                $ref: '#/components/schemas/User'
              type: array
        required: true
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: ""
        "200":
          description: no content
components:
  schemas:
    AboutData:
      example:
        LastRequestTime: 2000-01-23T04:56:07.000+00:00
        StartTime: 2000-01-23T04:56:07.000+00:00
        RunId: 1
        CurrentRequestCount: 6
        StartupRequestCount: 5
      properties:
        CurrentRequestCount:
          format: int32
          type: integer
        LastRequestTime:
          description: |-
            The time of the most recent request.

            This can be `None` if `/about` is the first request made.
          format: date-time
          type: string
          nullable: true
        RunId:
          format: int32
          type: integer
        StartTime:
          format: date-time
          type: string
        StartupRequestCount:
          format: int32
          type: integer
      required:
      - CurrentRequestCount
      - RunId
      - StartTime
      - StartupRequestCount
    Assignment:
      example:
        Users:
        - DomainSid: DomainSid
          DomainName: DomainName
          AccountSid: AccountSid
          AccountName: AccountName
        - DomainSid: DomainSid
          DomainName: DomainName
          AccountSid: AccountSid
          AccountName: AccountName
        Profile:
          PromptSecureDesktop: true
          DefaultElevationKind: AutoApprove
          Id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          ElevationSettings:
            Temporary:
              MaximumSeconds: 0
              Enabled: true
            Session:
              Enabled: true
          ElevationMethod: LocalAdmin
          Name: Name
      properties:
        Profile:
          $ref: '#/components/schemas/Profile'
        Users:
          items:
            $ref: '#/components/schemas/User'
          type: array
      required:
      - Profile
      - Users
    ElevateTemporaryPayload:
      example:
        Seconds: 0
      properties:
        Seconds:
          description: |-
            The number of seconds to elevate the user for.

            This must be between 1 and `i32::MAX`.
          format: int64
          minimum: 0.0
          type: integer
      required:
      - Seconds
    ElevationConfigurations:
      example:
        Temporary:
          MaximumSeconds: 0
          Enabled: true
        Session:
          Enabled: true
      properties:
        Session:
          $ref: '#/components/schemas/SessionElevationConfiguration'
        Temporary:
          $ref: '#/components/schemas/TemporaryElevationConfiguration'
      required:
      - Session
      - Temporary
    ElevationKind:
      enum:
      - AutoApprove
      - Confirm
      - ReasonApproval
      - Deny
      type: string
    ElevationMethod:
      enum:
      - LocalAdmin
      - VirtualAccount
      type: string
    Error:
      description: The original crate-wide error type.
      enum:
      - AccessDenied
      - NotFound
      - InvalidParameter
      - Internal
      - Cancelled
      type: string
    ErrorResponse:
      example:
        Kind: AccessDenied
        Win32Error: 0
      properties:
        Kind:
          $ref: '#/components/schemas/Error'
        Win32Error:
          format: int32
          minimum: 0.0
          type: integer
      required:
      - Kind
      - Win32Error
    GetProfilesMeResponse:
      description: |-
        Returns some information about the current user and active profiles.

        If there is no active profile, the `active` UUID will be full of zeroes.
      example:
        Active: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        Available:
        - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        Active:
          format: uuid
          type: string
        Available:
          items:
            format: uuid
            type: string
          type: array
      required:
      - Active
      - Available
    JitElevationLogPage:
      example:
        Results:
        - User:
            DomainSid: DomainSid
            DomainName: DomainName
            AccountSid: AccountSid
            AccountName: AccountName
          TargetPath: TargetPath
          Id: 0
          Timestamp: 1
          Success: 6
        - User:
            DomainSid: DomainSid
            DomainName: DomainName
            AccountSid: AccountSid
            AccountName: AccountName
          TargetPath: TargetPath
          Id: 0
          Timestamp: 1
          Success: 6
        TotalRecords: 0
        TotalPages: 0
      properties:
        Results:
          items:
            $ref: '#/components/schemas/JitElevationLogRow'
          type: array
        TotalPages:
          format: int32
          minimum: 0.0
          type: integer
        TotalRecords:
          format: int32
          minimum: 0.0
          type: integer
      required:
      - Results
      - TotalPages
      - TotalRecords
    JitElevationLogQueryOptions:
      example:
        User:
          DomainSid: DomainSid
          DomainName: DomainName
          AccountSid: AccountSid
          AccountName: AccountName
        EndTime: 0
        PageSize: 0
        PageNumber: 0
        StartTime: 5
        SortDescending: true
        SortColumn: SortColumn
      properties:
        EndTime:
          format: int64
          type: integer
        PageNumber:
          format: int32
          minimum: 0.0
          type: integer
        PageSize:
          format: int32
          minimum: 0.0
          type: integer
        SortColumn:
          type: string
        SortDescending:
          type: boolean
        StartTime:
          format: int64
          type: integer
        User:
          $ref: '#/components/schemas/User'
      required:
      - EndTime
      - PageNumber
      - PageSize
      - SortColumn
      - SortDescending
      - StartTime
    JitElevationLogRow:
      example:
        User:
          DomainSid: DomainSid
          DomainName: DomainName
          AccountSid: AccountSid
          AccountName: AccountName
        TargetPath: TargetPath
        Id: 0
        Timestamp: 1
        Success: 6
      properties:
        Id:
          format: int64
          type: integer
        Success:
          format: int64
          type: integer
        TargetPath:
          type: string
        Timestamp:
          format: int64
          type: integer
        User:
          $ref: '#/components/schemas/User'
      required:
      - Id
      - Success
      - TargetPath
      - Timestamp
      - User
    LaunchPayload:
      example:
        CreationFlags: 0
        WorkingDirectory: WorkingDirectory
        CommandLine: CommandLine
        StartupInfo:
          Desktop: Desktop
          XSize: 0
          YCountChars: 0
          YSize: 0
          FillAttribute: 0
          ShowWindow: 0
          X: 0
          ParentPid: 0
          Title: Title
          "Y": 0
          XCountChars: 0
          Flags: 0
        ExecutablePath: ExecutablePath
      properties:
        CommandLine:
          type: string
          nullable: true
        CreationFlags:
          format: int32
          minimum: 0.0
          type: integer
        ExecutablePath:
          type: string
          nullable: true
        StartupInfo:
          $ref: '#/components/schemas/StartupInfoDto'
        WorkingDirectory:
          type: string
          nullable: true
      required:
      - CreationFlags
    LaunchResponse:
      example:
        ThreadId: 0
        ProcessId: 0
      properties:
        ProcessId:
          format: int32
          minimum: 0.0
          type: integer
        ThreadId:
          format: int32
          minimum: 0.0
          type: integer
      required:
      - ProcessId
      - ThreadId
    OptionalId:
      example:
        Id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        Id:
          format: uuid
          type: string
          nullable: true
    PathIdParameter:
      properties:
        id:
          format: uuid
          type: string
      required:
      - id
    Profile:
      example:
        PromptSecureDesktop: true
        DefaultElevationKind: AutoApprove
        Id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        ElevationSettings:
          Temporary:
            MaximumSeconds: 0
            Enabled: true
          Session:
            Enabled: true
        ElevationMethod: LocalAdmin
        Name: Name
      properties:
        DefaultElevationKind:
          $ref: '#/components/schemas/ElevationKind'
        ElevationMethod:
          $ref: '#/components/schemas/ElevationMethod'
        ElevationSettings:
          $ref: '#/components/schemas/ElevationConfigurations'
        Id:
          format: uuid
          type: string
        Name:
          type: string
        PromptSecureDesktop:
          type: boolean
      required:
      - DefaultElevationKind
      - ElevationMethod
      - ElevationSettings
      - Id
      - Name
      - PromptSecureDesktop
    SessionElevationConfiguration:
      example:
        Enabled: true
      properties:
        Enabled:
          type: boolean
      required:
      - Enabled
    SessionElevationStatus:
      example:
        Enabled: true
      properties:
        Enabled:
          type: boolean
      required:
      - Enabled
    StartupInfoDto:
      example:
        Desktop: Desktop
        XSize: 0
        YCountChars: 0
        YSize: 0
        FillAttribute: 0
        ShowWindow: 0
        X: 0
        ParentPid: 0
        Title: Title
        "Y": 0
        XCountChars: 0
        Flags: 0
      properties:
        Desktop:
          type: string
          nullable: true
        FillAttribute:
          format: int32
          minimum: 0.0
          type: integer
        Flags:
          format: int32
          minimum: 0.0
          type: integer
        ParentPid:
          format: int32
          minimum: 0.0
          type: integer
          nullable: true
        ShowWindow:
          format: int32
          minimum: 0.0
          type: integer
        Title:
          type: string
          nullable: true
        X:
          format: int32
          minimum: 0.0
          type: integer
        XCountChars:
          format: int32
          minimum: 0.0
          type: integer
        XSize:
          format: int32
          minimum: 0.0
          type: integer
        "Y":
          format: int32
          minimum: 0.0
          type: integer
        YCountChars:
          format: int32
          minimum: 0.0
          type: integer
        YSize:
          format: int32
          minimum: 0.0
          type: integer
      required:
      - FillAttribute
      - Flags
      - ShowWindow
      - X
      - XCountChars
      - XSize
      - "Y"
      - YCountChars
      - YSize
    StatusResponse:
      example:
        Elevated: true
        Temporary:
          MaximumSeconds: 0
          TimeLeft: 0
          Enabled: true
        Session:
          Enabled: true
      properties:
        Elevated:
          type: boolean
        Session:
          $ref: '#/components/schemas/SessionElevationStatus'
        Temporary:
          $ref: '#/components/schemas/TemporaryElevationStatus'
      required:
      - Elevated
      - Session
      - Temporary
    TemporaryElevationConfiguration:
      example:
        MaximumSeconds: 0
        Enabled: true
      properties:
        Enabled:
          type: boolean
        MaximumSeconds:
          format: int64
          minimum: 0.0
          type: integer
      required:
      - Enabled
      - MaximumSeconds
    TemporaryElevationStatus:
      example:
        MaximumSeconds: 0
        TimeLeft: 0
        Enabled: true
      properties:
        Enabled:
          type: boolean
        MaximumSeconds:
          format: int64
          minimum: 0.0
          type: integer
        TimeLeft:
          format: int64
          minimum: 0.0
          type: integer
      required:
      - Enabled
      - MaximumSeconds
      - TimeLeft
    User:
      example:
        DomainSid: DomainSid
        DomainName: DomainName
        AccountSid: AccountSid
        AccountName: AccountName
      properties:
        AccountName:
          type: string
        AccountSid:
          type: string
        DomainName:
          type: string
        DomainSid:
          type: string
      required:
      - AccountName
      - AccountSid
      - DomainName
      - DomainSid

